# Generated by Django 3.2.4 on 2021-07-27 09:31

from django.db import migrations


def populate_category(apps, schema_editor):
    Category = apps.get_model('auctions', 'Category')

    categories = [
        'Fashion',
        'Toys',
        'Electronics',
        'Home',
        'Books',
        'Business & Industrial',
        'Clothing, Shoes & Accessories',
        'Collectibles',
        'Consumer Electronics',
        'Crafts',
        'Dolls & Bears',
        'Home & Garden',
        'Motors',
        'Pet Supplies',
        'Sporting Goods',
        'Sports Mem, Cards & Fan Shop',
        'Toys & Hobbies',
        'Antiques',
        'Computers/Tablets & Networking',
    ]

    for category in categories:
        Category.objects.create(name=category)


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_category),
    ]
